"""Public media proxy — serves order item videos/images through HTTPS.

Browsers block mixed-content (http:// MinIO URLs inside an https:// page).
This proxy lets the frontend reference ``/api/v1/media/{token}`` which is
always served over the same HTTPS origin.

Tokens are short-lived (1 h) HMAC-signed payloads containing the item_id.
They are generated by the lookup and order endpoints and never expose S3 keys.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Response, status
from sqlalchemy import select

from app.core.security import verify_media_token
from app.db.models import OrderItem
from app.db.session import session_scope
from app.services import storage

router = APIRouter(prefix="/media", tags=["media"])


@router.get("/{token}")
async def proxy_media(token: str) -> Response:
    """Stream an order item's video (or composite image) from S3."""
    item_id = verify_media_token(token)
    if item_id is None:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail="invalid or expired token")

    async with session_scope() as session:
        item = (
            await session.execute(select(OrderItem).where(OrderItem.id == item_id))
        ).scalar_one_or_none()

    if item is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND)

    is_multi = len(item.character_ids) > 1
    s3_key = item.video_s3_key if item.video_s3_key else (item.composite_image_s3_key if is_multi else None)
    if not s3_key:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="media not ready")

    data = storage.download_bytes(s3_key)
    content_type = "video/mp4" if item.video_s3_key else "image/png"
    return Response(
        content=data,
        media_type=content_type,
        headers={"Cache-Control": "private, max-age=3600"},
    )
